//Auth
export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

//Paging
export const CHANGE_PAGE = 'CHANGE_PAGE'



export const GET_TOPICS_SUCCESS = "GET_TOPICS_SUCCESS";

//For All
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const CREATE_DATA_SUCCESS = 'CREATE_DATA_SUCCESS';
export const EDIT_DATA_SUCCESS = 'EDIT_DATA_SUCCESS';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const CHANGE_STATUS_SUCCESS = 'CHANGE_STATUS_SUCCESS';


//Orther

export const IS_LOADING = "IS_LOADING";
export const NOT_LOADING = "NOT_LOADING";
