export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

//posts
export const GET_DATAS_BEGIN = "GET_DATAS_BEGIN";
export const GET_DATAS_SUCCESS = "GET_DATAS_SUCCESS";
export const GET_DATAS_ERROR = "GET_DATAS_ERROR";
// export const SET_MESSAGE = "SET_MESSAGE";
// export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_DATA_BEGIN = "CREATE_DATA_BEGIN";
export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS";
export const CREATE_DATA_ERROR = "CREATE_DATA_ERROR";

//For comment
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const ACCEPT_SHOW_FORM = "ACCEPT_SHOW_FORM";
export const NOT_ACCEPT_SHOW_FORM = "NOT_ACCEPT_SHOW_FORM";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const IS_REPLY_COMMENT = "IS_REPLY_COMMENT";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const INCREMENT_LIKE_COMMENT = "INCREMENT_LIKE_COMMENT";
export const DECREMENT_LIKE_COMMENT = "DECREMENT_LIKE_COMMENT";

//For post

export const INCREMENT_LIKE_POST = "INCREMENT_LIKE_POST";
export const DECREMENT_LIKE_POST = "DECREMENT_LIKE_POST";
export const GET_RECENT_POST = "GET_RECENT_POST";
export const CHANGEPAGE = "CHANGEPAGE";
