export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const MESSAGE = 'MESSAGE';

export const CHANGE_TAB = 'CHANGE_TAB';
export const CHANGE_PAGE = 'CHANGE_PAGE';


export const SET_MODAL_DATA = 'SET_MODAL_DATA';
export const WATCH_MODAL = 'WATCH_MODAL';
export const ADD_MODAL = 'ADD_MODAL';
export const EDIT_MODAL = 'EDIT MODAL';
//Login Logout
export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';


export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

//CRUD 
export const CREATE_DATA_BEGIN = 'CREATE_DATA_BEGIN';
export const CREATE_DATA_SUCCESS = 'CREATE_DATA_SUCCESS';
export const CREATE_DATA_ERROR = 'CREATE_DATA_ERROR';
export const GET_DATAS_BEGIN = 'GET_DATAS_BEGIN';
export const GET_DATAS_SUCCESS = 'GET_DATAS_SUCCESS';
export const GET_DATAS_ERROR = 'GET_DATAS_ERROR';
export const DELETE_DATA_BEGIN = 'DELETE_DATA_BEGIN';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const DELETE_DATA_ERROR = 'DELETE_DATA_ERROR';

//CRUD CATEGORIES
export const CREATE_CATEGORIES_BEGIN = 'CREATE_CATEGORIES_BEGIN';
export const CREATE_CATEGORIES_SUCCESS = 'CREATE_CATEGORIES_SUCCESS';
export const CREATE_CATEGORIES_ERROR = 'CREATE_CATEGORIES_ERROR';
export const GET_CATEGORIES_BEGIN = 'GET_CATEGORIES_BEGIN';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const DELETE_CATEGORY_BEGIN = 'DELETE_CATEGORY_BEGIN';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';